Repository felix642/1chipML, pull requests merged in 2023-01, with the labels that each got.

#29 Formatting the source code to comply with the LLVM standard
  src/.clang-format
  src/1chipml.h
  src/gauss_elimination.c
  src/gauss_elimination.h
  src/linear_congruential_random_generator.c
  src/linear_congruential_random_generator.h
  src/mc_integration.c
  src/mc_std.c
  src/mc_stratified_sampling.c
  src/poly_interpolation.c
  src/poly_interpolation.h
  tests/test_gauss_elimination.c
  tests/test_linear_congruential_random_generator.c
  tests/test_poly_interpolation.c
Labels: documentation

#34 Invalid permission poly interpolation
  tests/test_poly_interpolation.c
Labels: bug

#36 Added variables for makefile
  .gitignore
  Makefile
Labels: feature
